import Link from 'next/link';

const CONTACT_EMAIL = 'Abdurasaqadamolayinka@gmail.com';
const LAST_UPDATED = 'July 30, 2026';

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-lg font-bold text-white">{title}</h2>
      <div className="text-sm text-zinc-400 leading-relaxed space-y-3">{children}</div>
    </section>
  );
}

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#09090b] text-white p-8 max-w-4xl mx-auto space-y-8 font-sans pb-24">
      <div>
        <Link href="/login" className="text-xs text-violet-400 hover:underline">← Back to AMAI</Link>
        <h1 className="text-3xl font-bold mt-4">AMAI Privacy Policy</h1>
        <p className="text-xs text-zinc-500 mt-2">Last updated: {LAST_UPDATED}</p>
      </div>

      <p className="text-sm text-zinc-300 leading-relaxed">
        AMAI ("AMAI," "we," "us," or "our") provides an AI-powered content scheduling and
        publishing tool that lets you upload media, automatically generates captions and
        hashtags, and publishes or schedules that content to your own connected Instagram and
        TikTok accounts. This Privacy Policy explains what information we collect, how we use
        it, who we share it with, and the choices you have.
      </p>

      <Section title="1. Information We Collect">
        <p><strong className="text-zinc-200">Account information.</strong> When you register, we collect your email address and a securely hashed password. We never store your password in plain text.</p>
        <p><strong className="text-zinc-200">Connected platform data.</strong> When you connect Instagram, TikTok, or Google Drive, we receive an OAuth access token (and refresh token, where the platform issues one) and basic profile information the platform shares with us — such as your username/handle and account ID — so we can identify which account to publish to or sync from.</p>
        <p><strong className="text-zinc-200">Media you upload.</strong> Photos and videos you upload directly or sync from a connected Google Drive folder, so AMAI can analyze, caption, and publish them on your behalf.</p>
        <p><strong className="text-zinc-200">AI-generated content.</strong> Captions, hashtags, and content classifications generated by our AI provider (Google Gemini) based on your uploaded media, and a log of the prompts and completions used to generate them.</p>
        <p><strong className="text-zinc-200">Usage and activity data.</strong> Records of actions the AMAI Engine takes on your behalf — uploads processed, posts scheduled, publish attempts and their outcomes — so we can show you an activity feed and diagnose failures.</p>
      </Section>

      <Section title="2. How We Use Your Information">
        <p>We use the information above to:</p>
        <ul className="list-disc list-inside space-y-1">
          <li>Authenticate you and keep your account secure.</li>
          <li>Publish or schedule content to the Instagram and/or TikTok accounts you explicitly connect.</li>
          <li>Sync new files from a Google Drive folder you choose to connect.</li>
          <li>Generate captions, hashtags, and a suggested publishing schedule using AI analysis of your media.</li>
          <li>Show you the status of uploads, scheduled posts, and publishing activity.</li>
          <li>Diagnose and fix errors in the publishing pipeline.</li>
        </ul>
        <p>We do not sell your personal information, and we do not use your uploaded media or connected-account data to train AI models.</p>
      </Section>

      <Section title="3. Third-Party Services We Use">
        <p>AMAI is built on top of the following third-party services, each of which processes a limited slice of your data strictly to provide the functionality described:</p>
        <ul className="list-disc list-inside space-y-1">
          <li><strong className="text-zinc-200">Meta Graph API (Instagram)</strong> — to publish content and read basic account/page information for accounts you connect.</li>
          <li><strong className="text-zinc-200">TikTok API</strong> — to publish content and read basic profile information for accounts you connect.</li>
          <li><strong className="text-zinc-200">Google Drive API</strong> — to list and download files from a folder you explicitly select, read-only.</li>
          <li><strong className="text-zinc-200">Google Gemini API</strong> — to analyze uploaded images and generate captions/hashtags.</li>
          <li><strong className="text-zinc-200">Vercel Blob storage</strong> — to store the media files you upload.</li>
          <li><strong className="text-zinc-200">Supabase (PostgreSQL)</strong> — our application database, storing account, content, and scheduling records.</li>
        </ul>
        <p>Each of these providers has its own privacy policy governing how it handles data in transit to or from its service.</p>
      </Section>

      <Section title="4. Data Security">
        <p>OAuth access and refresh tokens for every connected platform (Instagram, TikTok, Google) are encrypted at rest using AES-256 before being stored, and are only decrypted in-memory at the moment a request needs to use them. All traffic between your browser and AMAI, and between AMAI and every third-party API it calls, is encrypted in transit via HTTPS/TLS. Access to the application is gated by JSON Web Token (JWT) authentication scoped to your account and the specific brands/workspaces you belong to.</p>
      </Section>

      <Section title="5. Data Retention & Deletion">
        <p>We retain your account data, uploaded media, and activity history for as long as your account remains active, so you can review past posts and re-use past uploads. You can disconnect any connected platform account at any time from within AMAI, which immediately revokes our ability to act on that account and deletes the stored token. To request full deletion of your account and associated data, contact us at the email below — we will delete it within a reasonable time, except where we're required to retain records for legal or fraud-prevention purposes.</p>
      </Section>

      <Section title="6. Your Rights and Choices">
        <ul className="list-disc list-inside space-y-1">
          <li>You can disconnect Instagram, TikTok, or Google Drive at any time from AMAI's settings.</li>
          <li>You can delete individual uploaded media files and scheduled posts from within the app.</li>
          <li>You can request a copy of the personal data we hold about you.</li>
          <li>You can request deletion of your account and all associated data.</li>
        </ul>
        <p>To exercise any of these rights, email us at the address below.</p>
      </Section>

      <Section title="7. Children's Privacy">
        <p>AMAI is not directed to, and does not knowingly collect information from, anyone under the age of 16. If you believe a minor has provided us with personal information, contact us and we will delete it.</p>
      </Section>

      <Section title="8. Changes to This Policy">
        <p>We may update this Privacy Policy from time to time. Material changes will be reflected by updating the "Last updated" date above. Continued use of AMAI after a change constitutes acceptance of the updated policy.</p>
      </Section>

      <Section title="9. Contact Us">
        <p>Questions about this policy or your data? Email <a href={`mailto:${CONTACT_EMAIL}`} className="text-violet-400 hover:underline">{CONTACT_EMAIL}</a>.</p>
      </Section>
    </div>
  );
}
